apiVersion: v2
name: synapse
description: A Helm chart to deploy matrix synapse server. https://github.com/matrix-org/synapse
type: application
version: 0.2.0
appVersion: v1.26.0
home: https://github.com/sudermanjr/charts/tree/master/charts/synapse
keywords:
  - matrix
  - synapse
sources:
  - https://github.com/matrix-org/synapse/
maintainers:
  - name: sudermanjr
